CREATE TABLE IF NOT EXISTS trips (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  route_name VARCHAR(255) NOT NULL,
  start_date VARCHAR(100) NOT NULL,
  end_date VARCHAR(100) NOT NULL,
  pilgrims_count INT DEFAULT 1,
  guide_name VARCHAR(150),
  status VARCHAR(50) DEFAULT 'قيد التنفيذ',
  program_name VARCHAR(255),
  route_path VARCHAR(255),
  program_type VARCHAR(100),
  expected_duration VARCHAR(100),
  dominant_nationality VARCHAR(100),
  airline VARCHAR(150),
  flight_number VARCHAR(100),
  airport_hub VARCHAR(150),
  makkah_hotel VARCHAR(150),
  makkah_stay VARCHAR(100),
  madinah_hotel VARCHAR(150),
  madinah_stay VARCHAR(100),
  transport_company VARCHAR(150),
  transport_type VARCHAR(150),
  bus_number VARCHAR(100),
  driver_name VARCHAR(150),
  driver_phone VARCHAR(100),
  supervisor_name VARCHAR(150),
  supervisor_phone VARCHAR(100),
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
